comment: false
ignore:
- "**/generated/"
- "**/examples/"
- "**/spec/*"
flags:
  stellar-base:
    paths:
      - base/
  stellar-horizon:
    paths:
      - horizon/
  stellar-sdk:
    paths:
      - sdk/
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        flags:
          - stellar-base
          - stellar-horizon
          - stellar-sdk
      stellar-base:
        flags:
          - stellar-base
      stellar-horizon:
        flags:
          - stellar-horizon
      stellar-sdk:
        flags:
          - stellar-sdk
    patch:
      default:
        informational: true
        threshold: 1%
        paths:
        - "*/lib/"
