# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
  versioning-strategy: "increase-if-necessary"
- package-ecosystem: "bundler"
  directory: "/base"
  schedule:
    interval: "daily"
  allow:
  - dependency-type: "direct"
  labels:
  - "dependencies"
  - "stellar-base"
- package-ecosystem: "bundler"
  directory: "/sdk"
  schedule:
    interval: "daily"
  allow:
  - dependency-type: "direct"
  labels:
  - "dependencies"
  - "stellar-sdk"
