# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "github-actions"
  # Check for updates to GitHub Actions every week
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore(ci)"
- package-ecosystem: "bundler"
  # Check for for ruby deps update daily
  directory: "/"
  schedule:
    interval: "daily"
  versioning-strategy: "increase-if-necessary"
  allow:
    - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
    prefix-development: "core(dev-deps)"
  groups:
    deps:
      dependency-type: "production"
    dev-deps:
      dependency-type: "development"
