version: "2"
plugins:
  bundler-audit:
    enabled: false
  editorconfig:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
- "**/*.x"
- "**/LICENSE"
- "**/generated/"
- "**/examples/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
