---
# Source must be funded already
# Use https://www.stellar.org/laboratory/#account-creator?network=test
# These ones in the sample are just randomly generated ones; enough for tests
# to pass (as long as we're not re-recording)
source_seed: "SDSOGZVZWG3DMCXZCPEVLRUTNZAYBHQR3VSCMWC6XJANBM7352UAMNMJ"
source_address: "GDE2KTIZGRWMFGZMKLRNW3KA4ONOGIKZ4MTDXKCSZUPPLLJ2ICWCFT4Z"

# Channel must be funded as well, but put a real address (not funded is fine)
# so that Travis will still pass
channel_address: "GCJUEPBDWM7YEHU4EJVZK5AS477VYL3H6Q45Q2HLFBYK56PV7QQZHR2Z"
channel_seed: "SAZC7V23FZ3UZGP2HVNVJ2JMKUDBNOQLFIKOZ5QJ7JWONYRD2ZQTRUYK"
