name: release

on:
  workflow_dispatch:
  push:
    branches: [ main, master, "chore/release-workflow" ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      with:
        path: "base/"
        release-type: ruby
        package-name: stellar-base
        bump-minor-pre-major: true
        version-file: "base/lib/stellar/base/version.rb"

#    # The following steps only run when release was created
#    - name: Checkout code if release was created
#      if: ${{ steps.release.outputs.release_created }}
#      uses: actions/checkout@v2
#    - name: Setup Ruby
#      if: ${{ steps.release.outputs.release_created }}
#      uses: ruby/setup-ruby@v1
#      with:
#        ruby-version: 2.7
#        bundler-cache: true
#    - name: Publish to GPR
#      if: ${{ steps.release.outputs.release_created }}
#      run: |
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        gem build *.gemspec
#        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
#      env:
#        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
#        OWNER: ${{ github.repository_owner }}
#
#    - name: Publish to RubyGems
#      if: ${{ steps.release.outputs.release_created }}
#      run: |
#        mkdir -p $HOME/.gem
#        touch $HOME/.gem/credentials
#        chmod 0600 $HOME/.gem/credentials
#        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
#        gem build *.gemspec
#        gem push *.gem
#      env:
#        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
